#controller accueil
accueil:
    path: /
    controller: App\Controller\AccueilController::index
#controller visiteur
visiteur:
    path: /visiteur
    controller: App\Controller\VisiteurController::index
donnerDate:
    path: /visiteur/menu/donnerDate
    controller: App\Controller\VisiteurController::donnerDate
renseigner:
    path: /visiteur/menu/renseigner
    controller: App\Controller\VisiteurController::renseigner
creerHF:
    path: /visiteur/menu/creerHF
    controller: App\Controller\VisiteurController::creerHF

#controller comptable
comptable:
    path: /comptable
    controller: App\Controller\ComptableController::index
choisirVisMois:
    path: /comptable/choixVisMois
    controller: App\Controller\ComptableController::choisirVisMois
actualiseFrais:
    path: /comptable/actualiseFrais/{idFraisForfait}
    controller: App\Controller\ComptableController::actualiseFrais