<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJZc2MI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJZc2MI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJZc2MI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJZc2MI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}


return new \ContainerXJZc2MI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XJZc2MI',
    'container.build_id' => 'bc559eb1',
    'container.build_time' => 1606676991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJZc2MI');

