<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0wfjVc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0wfjVc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA0wfjVc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA0wfjVc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA0wfjVc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A0wfjVc',
    'container.build_id' => '481ac99b',
    'container.build_time' => 1601648457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0wfjVc');
