<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], []],
    'visiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::index'], [], [['text', '/visiteur']], [], []],
    'menuVisiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::menu'], [], [['text', '/visiteur/menu']], [], []],
    'donnerDate' => [[], ['_controller' => 'App\\Controller\\VisiteurController::donnerDate'], [], [['text', '/visiteur/menu/donnerDate']], [], []],
    'renseigner' => [[], ['_controller' => 'App\\Controller\\VisiteurController::renseigner'], [], [['text', '/visiteur/menu/renseigner']], [], []],
    'comptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::index'], [], [['text', '/comptable']], [], []],
];
